const CAT_PT: Record<string, string> = {
  interactive:      'interativo',
  interativo:       'interativo',
  data:             'dados',
  dados:            'dados',
  newsgame:         'newsgame',
  map:              'mapa',
  mapa:             'mapa',
  maps:             'mapas',
  mapas:            'mapas',
  scrollytelling:   'scrollytelling',
  quiz:             'quiz',
  chart:            'gráfico',
  'data journalism':'jornalismo de dados',
  visualization:    'visualização',
  visualização:     'visualização',
  analysis:         'análise',
  análise:          'análise',
  election:         'eleições',
  eleições:         'eleições',
  society:          'sociedade',
  sociedade:        'sociedade',
  economy:          'economia',
  economia:         'economia',
  politics:         'política',
  política:         'política',
  environment:      'ambiente',
  ambiente:         'ambiente',
};

const CAT_EN: Record<string, string> = {
  interativo:            'interactive',
  interactive:           'interactive',
  dados:                 'data',
  data:                  'data',
  newsgame:              'newsgame',
  mapa:                  'map',
  map:                   'map',
  mapas:                 'maps',
  maps:                  'maps',
  scrollytelling:        'scrollytelling',
  quiz:                  'quiz',
  gráfico:               'chart',
  chart:                 'chart',
  'jornalismo de dados': 'data journalism',
  'data journalism':     'data journalism',
  visualização:          'visualisation',
  visualization:         'visualisation',
  análise:               'analysis',
  analysis:              'analysis',
  eleições:              'elections',
  election:              'elections',
  sociedade:             'society',
  society:               'society',
  economia:              'economy',
  economy:               'economy',
  política:              'politics',
  politics:              'politics',
  ambiente:              'environment',
  environment:           'environment',
};

export function translateCat(cat: string, lang: string): string {
  const key = cat.toLowerCase().trim();
  const map = lang === 'pt' ? CAT_PT : CAT_EN;
  return map[key] ?? cat;
}
